# IMPORTANT! These offsets might be different on your system!

[[sections]]
name = ".dbl_text"

#test5
#values = [
#    {type = "none", offset = 0x0},
#    {type = "fixed", offset = 0x22, bit = 0, sign = '+'}, # 0f 84 16 00 00 00 : je 20189d <old_main+0x3d>
#    {type = "fixed", offset = 0x54, bit = 7, sign = '+'}, # c7 45 ec 07 00 00 00 : movl $0x7,-0x14(%rbp)
#    {type = "fixed", offset = 0x7b, bit = 4, sign = '+'}  # 03 45 f8 : add -0x8(%rbp),%eax
#]

#test7
#values = [
#    {type = "fixed", offset = 0x50, bit = 0, sign = '+'}, # 0f 84 16 00 00 00 : je 20189d <old_main+0x3d>
#    {type = "fixed", offset = 0x82, bit = 7, sign = '+'}, # c7 45 ec 07 00 00 00 : movl $0x7,-0x14(%rbp)
#    {type = "fixed", offset = 0xa9, bit = 4, sign = '+'}, # 03 45 f8 : add -0x8(%rbp),%eax
#    {type = "range", start_offset = 0xcf, range = 4, normal_dest = 0xe9, flipped_dest = 0xd3}, # 0f 84 16 00 00 00 : je 0x201909 <old_main+0xbb>
#    {type = "range", start_offset = 0xfb, range = 4, normal_dest = 0x0, flipped_dest = 0x17}, # e8 01 ff ff ff : callq 0x201820 <fn1>
#]

